Задание "Таймер"
en0t-poloskun/test-guru pull request #16
Opened 2021-07-13 13:33 UTC by en0t-poloskun

2021-07-13 15:40 UTC, VidgarVii requested changes

2021-07-13 15:40 UTC, VidgarVii commented on app/javascript/utilities/timer.js
> +        window.location.href = window.location.href + "/result"
тут лучше сабмитеть форму. ЧТобы на сервере завершился тест

2021-07-13 15:40 UTC, VidgarVii commented on app/javascript/packs/application.js
> +  if (timer) { new Timer(timer.dataset.timeLeft).countdown() }
`if (timer) new Timer(timer.dataset.timeLeft).countdown()`

2021-07-13 15:40 UTC, VidgarVii commented on app/javascript/utilities/timer.js
> +class Timer {
export default class Timer
и не нужна будет 30 строка

2021-07-13 15:40 UTC, VidgarVii commented on app/models/test.rb
> +  validates :timer, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
задание не подразумевало, что таймер должен быть обязателен

2021-07-14 13:56 UTC, VidgarVii requested changes

2021-07-14 13:56 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      return
1 вспоминай как работает redirect_to
2 по логике если время вышло то тест можно считать завершенным. А такая проверка у тебя уже есть. Надо дополнить метод
3 смотрится ужасно

2021-07-15 07:01 UTC, VidgarVii requested changes

2021-07-15 07:01 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      TestsMailer.completed_tests(@test_passage).deliver_now if @test_passage.finished?
чем отличается finished от completed?
по моему 2 раза одно и то же спрашиваем

2021-07-15 07:01 UTC, VidgarVii commented on app/models/test_passage.rb
> +  scope :passed, -> { select(&:passed?) }
scope всегда должен возвращать ActiveRecord_Relation
У тебя сейчас простой массив. И продолжить использовать методы обращения к БД уже не получиться

2021-07-15 07:01 UTC, VidgarVii commented on app/models/test_passage.rb
> +    finished? or time_is_over?
ни каких or and. только || и &&.
Разная последовательность вызовов. можно потом запутаться

2021-07-15 07:01 UTC, VidgarVii commented on app/models/test_passage.rb
> +  # например, он используется в методе passed?, чтобы тест не считался успешно пройденным, если время вышло
если время вышло можно так же сбрасывать current_question на нил

2021-07-15 07:01 UTC, VidgarVii commented on app/models/test_passage.rb
> +    result >= 85 and finished?
а ведь может случиться так, что юзер набрал более 85 очков, но не уложился по времени. Ведь это можно считать что тест пройден успешно?

2021-07-15 07:01 UTC, VidgarVii commented on app/models/test_passage.rb
> +    return unless test.timer
методы предикаты должны возвращать только true/false

2021-07-15 07:01 UTC, VidgarVii commented on app/views/admins/tests/show.html.erb
> +</p>
если не задан таймер. можно ни чего не выводить

2021-07-15 08:23 UTC, en0t-poloskun commented on app/models/test_passage.rb
> +    result >= 85 and finished?
В задании было написано, что при истечении времени таймера тест считается не пройденным.

2021-07-16 10:43 UTC, merged